[package]
name = "chippy8"
version = "0.1.0"
authors = ["glitchy <v.smit.mail@gmail.com>"]
edition = "2018"

[dependencies]
hex = "0.3.2"
nom = "5.0.0"
rand = "0.7.0"
glium = "0.25.1"
image = "0.22.1"